# Generated by Django 5.1 on 2024-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
