# Generated by Django 5.1 on 2024-08-23 18:01

import app_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                default=app_accounts.models.default_avatar, upload_to="profile_images/"
            ),
        ),
    ]
