# Generated by Django 5.1 on 2024-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(max_length=500, null=True, upload_to='photo_for_users'),
        ),
    ]
