# Generated by Django 5.1 on 2024-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_photo", "0002_alter_car_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_image",
            name="image",
            field=models.FileField(max_length=500, upload_to="photo_for_users"),
        ),
    ]
